---

# TODO?
# use "pecl channel-update pecl.php.net"

# - name: clear pecl cache
#   php_pecl:
#     state: "clear-cache"
#   register: php_pecl_pecl_result
#
# - name: d
#   debug:
#     msg: "{{ php_pecl_pecl_result }}"

- name: pecl stuff
  php_pecl:
    state: install
    packages: "{{ php_pecl_extensions }}"
    php_config:
      module_dir: /etc/php/8.2/mods-available
      config_dirs:
        - /etc/php/8.2/cli/conf.d
        - /etc/php/8.2/fpm/conf.d

  register: php_pecl_pecl_result

# - name: pecl stuff
#   block:
#     - name: Install PECL libaries.
#       shell: "yes '' | {{ php_pecl_install_command }} {{ item }}"
#       register: php_pecl_pecl_result
#       changed_when: php_pecl_pecl_result is succeeded
#       failed_when: "not (('already installed' in php_pecl_pecl_result.stdout) or ('install ok:' in php_pecl_pecl_result.stdout))"
#       loop: "{{ php_pecl_extensions }}"

- name: d
  debug:
    msg: "{{ php_pecl_pecl_result }}"

...
