---

- name: include OS specific configuration
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        # eg. debian-10 / ubuntu-20 / centos-8 / oraclelinux-8
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
        # eg. archlinux-systemd / archlinux-openrc
        - "{{ ansible_distribution | lower }}-{{ ansible_service_mgr | lower }}.yml"
        # eg. debian / ubuntu / centos / oraclelinux
        - "{{ ansible_distribution | lower }}.yml"
        # eg. redhat / debian
        - "{{ ansible_os_family | lower }}.yml"
        # artixlinux
        - "{{ ansible_os_family | lower | replace(' ', '') }}.yml"
        - default.yml
      skip: true

- name: update package cache
  ansible.builtin.package:
    update_cache: true

# TODO
# detect installed pecl extensions and versions

- name: define dependecies
  set_fact:
    php_pecl_build_dependecies: "{{ php_pecl_defaults_build_dependecies + php_pecl_extensions | dependencies() }}"

- name: d
  debug:
    msg: "{{ php_pecl_build_dependecies }}"

- name: install build dependencies
  become: true
  ansible.builtin.package:
    name: "{{ php_pecl_build_dependecies }}"
    state: present
  when:
    - php_pecl_build_dependecies | default([]) | count > 0
